//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirastyarWordAddin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Config_UserDictionaryPath {
            get {
                return ((string)(this["Config_UserDictionaryPath"]));
            }
            set {
                this["Config_UserDictionaryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint Config_EditDistance {
            get {
                return ((uint)(this["Config_EditDistance"]));
            }
            set {
                this["Config_EditDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public uint Config_MaxSuggestions {
            get {
                return ((uint)(this["Config_MaxSuggestions"]));
            }
            set {
                this["Config_MaxSuggestions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + F7")]
        public string Config_Shortcut_VirastyarCheckSpell_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarCheckSpell_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarCheckSpell_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + F8")]
        public string Config_Shortcut_VirastyarCheckDates_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarCheckDates_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarCheckDates_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + Control + F8")]
        public string Config_Shortcut_VirastyarCheckNumbers_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarCheckNumbers_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarCheckNumbers_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + F5")]
        public string Config_Shortcut_VirastyarCheckPunctuation_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarCheckPunctuation_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarCheckPunctuation_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + F6")]
        public string Config_Shortcut_VirastyarPinglishConvert_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarPinglishConvert_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarPinglishConvert_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control + Alt + F7")]
        public string Config_Shortcut_VirastyarRefineAllCharacters_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarRefineAllCharacters_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarRefineAllCharacters_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31")]
        public int RefineCategoriesFlag {
            get {
                return ((int)(this["RefineCategoriesFlag"]));
            }
            set {
                this["RefineCategoriesFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RefineHalfSpacePositioning {
            get {
                return ((bool)(this["RefineHalfSpacePositioning"]));
            }
            set {
                this["RefineHalfSpacePositioning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RefineIgnoreListConcated {
            get {
                return ((string)(this["RefineIgnoreListConcated"]));
            }
            set {
                this["RefineIgnoreListConcated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Config_Shortcut_SynonymSuggestion {
            get {
                return ((string)(this["Config_Shortcut_SynonymSuggestion"]));
            }
            set {
                this["Config_Shortcut_SynonymSuggestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Config_Shortcut_RhymeSuggestion {
            get {
                return ((string)(this["Config_Shortcut_RhymeSuggestion"]));
            }
            set {
                this["Config_Shortcut_RhymeSuggestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source={0}")]
        public string SynConnectionStringFormat {
            get {
                return ((string)(this["SynConnectionStringFormat"]));
            }
            set {
                this["SynConnectionStringFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Synonyms.mdb")]
        public string SynDBBaseFileName {
            get {
                return ((string)(this["SynDBBaseFileName"]));
            }
            set {
                this["SynDBBaseFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WordCompletionCompleteWithoutHotKey {
            get {
                return ((bool)(this["WordCompletionCompleteWithoutHotKey"]));
            }
            set {
                this["WordCompletionCompleteWithoutHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int WordCompletionMinWordLength {
            get {
                return ((int)(this["WordCompletionMinWordLength"]));
            }
            set {
                this["WordCompletionMinWordLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WordCompletionInsertSpace {
            get {
                return ((bool)(this["WordCompletionInsertSpace"]));
            }
            set {
                this["WordCompletionInsertSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int WordCompletionFontSize {
            get {
                return ((int)(this["WordCompletionFontSize"]));
            }
            set {
                this["WordCompletionFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpellChecker_CustomDictionaries {
            get {
                return ((string)(this["SpellChecker_CustomDictionaries"]));
            }
            set {
                this["SpellChecker_CustomDictionaries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SpellChecker_CustomDictionariesSelectionFlag {
            get {
                return ((int)(this["SpellChecker_CustomDictionariesSelectionFlag"]));
            }
            set {
                this["SpellChecker_CustomDictionariesSelectionFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpellChecker_MainDictionaryPath {
            get {
                return ((string)(this["SpellChecker_MainDictionaryPath"]));
            }
            set {
                this["SpellChecker_MainDictionaryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpellChecker_MainDictionarySelected {
            get {
                return ((bool)(this["SpellChecker_MainDictionarySelected"]));
            }
            set {
                this["SpellChecker_MainDictionarySelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpellChecker_CustomDictionariesDescription {
            get {
                return ((string)(this["SpellChecker_CustomDictionariesDescription"]));
            }
            set {
                this["SpellChecker_CustomDictionariesDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpellChecker_VocabSpaceCorrection {
            get {
                return ((bool)(this["SpellChecker_VocabSpaceCorrection"]));
            }
            set {
                this["SpellChecker_VocabSpaceCorrection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpellChecker_HeYeConvertion {
            get {
                return ((bool)(this["SpellChecker_HeYeConvertion"]));
            }
            set {
                this["SpellChecker_HeYeConvertion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreprocessSpell_RefineHaa {
            get {
                return ((bool)(this["PreprocessSpell_RefineHaa"]));
            }
            set {
                this["PreprocessSpell_RefineHaa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreprocessSpell_RefineMee {
            get {
                return ((bool)(this["PreprocessSpell_RefineMee"]));
            }
            set {
                this["PreprocessSpell_RefineMee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreprocessSpell_RefineHeYe {
            get {
                return ((bool)(this["PreprocessSpell_RefineHeYe"]));
            }
            set {
                this["PreprocessSpell_RefineHeYe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreprocessSpell_RefineBe {
            get {
                return ((bool)(this["PreprocessSpell_RefineBe"]));
            }
            set {
                this["PreprocessSpell_RefineBe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreprocessSpell_RefineAllAffixes {
            get {
                return ((bool)(this["PreprocessSpell_RefineAllAffixes"]));
            }
            set {
                this["PreprocessSpell_RefineAllAffixes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpellChecker_DontCheckSingleLetters {
            get {
                return ((bool)(this["SpellChecker_DontCheckSingleLetters"]));
            }
            set {
                this["SpellChecker_DontCheckSingleLetters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + Control + F6")]
        public string Config_Shortcut_VirastyarPinglishConvertAll_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarPinglishConvertAll_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarPinglishConvertAll_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + Control + F7")]
        public string Config_Shortcut_VirastyarPreCheckSpell_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarPreCheckSpell_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarPreCheckSpell_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Config_Shortcur_VirastyarCheckAllPunctuation_Action {
            get {
                return ((string)(this["Config_Shortcur_VirastyarCheckAllPunctuation_Action"]));
            }
            set {
                this["Config_Shortcur_VirastyarCheckAllPunctuation_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Config_Shortcut_VirastyarAddinSettings_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarAddinSettings_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarAddinSettings_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Config_Shortcut_VirastyarAbout_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarAbout_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarAbout_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + Control + Space")]
        public string Config_Shortcut_VirastyarAutoComplete_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarAutoComplete_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarAutoComplete_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TipOfTheDayShowOnStartup {
            get {
                return ((bool)(this["TipOfTheDayShowOnStartup"]));
            }
            set {
                this["TipOfTheDayShowOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Updater_LastCheckedVersion {
            get {
                return ((string)(this["Updater_LastCheckedVersion"]));
            }
            set {
                this["Updater_LastCheckedVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2011-01-01")]
        public global::System.DateTime LogReport_LastSentLog {
            get {
                return ((global::System.DateTime)(this["LogReport_LastSentLog"]));
            }
            set {
                this["LogReport_LastSentLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogReport_AutomaticReport {
            get {
                return ((bool)(this["LogReport_AutomaticReport"]));
            }
            set {
                this["LogReport_AutomaticReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int LogReport_AutomaticReportInterval {
            get {
                return ((int)(this["LogReport_AutomaticReportInterval"]));
            }
            set {
                this["LogReport_AutomaticReportInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + F7")]
        public string Config_Shortcut_SpellCheck {
            get {
                return ((string)(this["Config_Shortcut_SpellCheck"]));
            }
            set {
                this["Config_Shortcut_SpellCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + F8")]
        public string Config_Shortcut_DateCheck {
            get {
                return ((string)(this["Config_Shortcut_DateCheck"]));
            }
            set {
                this["Config_Shortcut_DateCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + F8")]
        public string Config_Shortcut_NumberCheck {
            get {
                return ((string)(this["Config_Shortcut_NumberCheck"]));
            }
            set {
                this["Config_Shortcut_NumberCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + F7")]
        public string Config_Shortcut_PunctuationCheck {
            get {
                return ((string)(this["Config_Shortcut_PunctuationCheck"]));
            }
            set {
                this["Config_Shortcut_PunctuationCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control + Alt + F2")]
        public string Config_Shortcut_PinglishCheck {
            get {
                return ((string)(this["Config_Shortcut_PinglishCheck"]));
            }
            set {
                this["Config_Shortcut_PinglishCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + F9")]
        public string Config_Shortcut_RefineCharachters {
            get {
                return ((string)(this["Config_Shortcut_RefineCharachters"]));
            }
            set {
                this["Config_Shortcut_RefineCharachters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control +Shift + Space")]
        public string Config_Shortcut_WordCompletion {
            get {
                return ((string)(this["Config_Shortcut_WordCompletion"]));
            }
            set {
                this["Config_Shortcut_WordCompletion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int WordCompletionSugCount {
            get {
                return ((int)(this["WordCompletionSugCount"]));
            }
            set {
                this["WordCompletionSugCount"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.virastyar.ir/LatestVersion.txt")]
        public string Updater_LatestVersionUrl {
            get {
                return ((string)(this["Updater_LatestVersionUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.virastyar.ir/Download.html")]
        public string Updater_DownloadUrl {
            get {
                return ((string)(this["Updater_DownloadUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.virastyar.ir/ChangeLog.txt")]
        public string Updater_ChangeLogUrl {
            get {
                return ((string)(this["Updater_ChangeLogUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.virastyar.ir/ReleaseNotes.txt")]
        public string Updater_ReleaseNotesUrl {
            get {
                return ((string)(this["Updater_ReleaseNotesUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.virastyar.ir/log.php")]
        public string LogReport_Url {
            get {
                return ((string)(this["LogReport_Url"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InstallationGuid {
            get {
                return ((string)(this["InstallationGuid"]));
            }
            set {
                this["InstallationGuid"] = value;
            }
        }
    }
}
