//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirastyarWordAddin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.virastyar.ir/LatestVersion.txt")]
        public string Updater_LatestVersionUrl {
            get {
                return ((string)(this["Updater_LatestVersionUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.virastyar.ir/ChangeLog.txt")]
        public string Updater_ChangeLogUrl {
            get {
                return ((string)(this["Updater_ChangeLogUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.virastyar.ir/ReleaseNotes.txt")]
        public string Updater_ReleaseNotesUrl {
            get {
                return ((string)(this["Updater_ReleaseNotesUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.virastyar.ir/log.php")]
        public string LogReport_Url {
            get {
                return ((string)(this["LogReport_Url"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpellChecker_UserDictionaryPath {
            get {
                return ((string)(this["SpellChecker_UserDictionaryPath"]));
            }
            set {
                this["SpellChecker_UserDictionaryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SpellChecker_EditDistance {
            get {
                return ((int)(this["SpellChecker_EditDistance"]));
            }
            set {
                this["SpellChecker_EditDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int SpellChecker_MaxSuggestions {
            get {
                return ((int)(this["SpellChecker_MaxSuggestions"]));
            }
            set {
                this["SpellChecker_MaxSuggestions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpellChecker_CustomDictionaries {
            get {
                return ((string)(this["SpellChecker_CustomDictionaries"]));
            }
            set {
                this["SpellChecker_CustomDictionaries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SpellChecker_CustomDictionariesSelectionFlag {
            get {
                return ((int)(this["SpellChecker_CustomDictionariesSelectionFlag"]));
            }
            set {
                this["SpellChecker_CustomDictionariesSelectionFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpellChecker_CustomDictionariesDescription {
            get {
                return ((string)(this["SpellChecker_CustomDictionariesDescription"]));
            }
            set {
                this["SpellChecker_CustomDictionariesDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpellChecker_MainDictionaryPath {
            get {
                return ((string)(this["SpellChecker_MainDictionaryPath"]));
            }
            set {
                this["SpellChecker_MainDictionaryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpellChecker_MainDictionarySelected {
            get {
                return ((bool)(this["SpellChecker_MainDictionarySelected"]));
            }
            set {
                this["SpellChecker_MainDictionarySelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreprocessSpell_CorrectPostfix {
            get {
                return ((bool)(this["PreprocessSpell_CorrectPostfix"]));
            }
            set {
                this["PreprocessSpell_CorrectPostfix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreprocessSpell_CorrectPrefix {
            get {
                return ((bool)(this["PreprocessSpell_CorrectPrefix"]));
            }
            set {
                this["PreprocessSpell_CorrectPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31")]
        public int RefineCategoriesFlag {
            get {
                return ((int)(this["RefineCategoriesFlag"]));
            }
            set {
                this["RefineCategoriesFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RefineHalfSpacePositioning {
            get {
                return ((bool)(this["RefineHalfSpacePositioning"]));
            }
            set {
                this["RefineHalfSpacePositioning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RefineNormalizeHeYe {
            get {
                return ((bool)(this["RefineNormalizeHeYe"]));
            }
            set {
                this["RefineNormalizeHeYe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RefineLongHeYeToShort {
            get {
                return ((bool)(this["RefineLongHeYeToShort"]));
            }
            set {
                this["RefineLongHeYeToShort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RefineShortHeYeToLong {
            get {
                return ((bool)(this["RefineShortHeYeToLong"]));
            }
            set {
                this["RefineShortHeYeToLong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RefineIgnoreListConcated {
            get {
                return ((string)(this["RefineIgnoreListConcated"]));
            }
            set {
                this["RefineIgnoreListConcated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int WordCompletionSugCount {
            get {
                return ((int)(this["WordCompletionSugCount"]));
            }
            set {
                this["WordCompletionSugCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WordCompletionCompleteWithoutHotKey {
            get {
                return ((bool)(this["WordCompletionCompleteWithoutHotKey"]));
            }
            set {
                this["WordCompletionCompleteWithoutHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int WordCompletionMinWordLength {
            get {
                return ((int)(this["WordCompletionMinWordLength"]));
            }
            set {
                this["WordCompletionMinWordLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WordCompletionInsertSpace {
            get {
                return ((bool)(this["WordCompletionInsertSpace"]));
            }
            set {
                this["WordCompletionInsertSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int WordCompletionFontSize {
            get {
                return ((int)(this["WordCompletionFontSize"]));
            }
            set {
                this["WordCompletionFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TipOfTheDayShowOnStartup {
            get {
                return ((bool)(this["TipOfTheDayShowOnStartup"]));
            }
            set {
                this["TipOfTheDayShowOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Updater_LastCheckedVersion {
            get {
                return ((string)(this["Updater_LastCheckedVersion"]));
            }
            set {
                this["Updater_LastCheckedVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2011-01-01")]
        public global::System.DateTime LogReport_LastSentLog {
            get {
                return ((global::System.DateTime)(this["LogReport_LastSentLog"]));
            }
            set {
                this["LogReport_LastSentLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogReport_AutomaticReport {
            get {
                return ((bool)(this["LogReport_AutomaticReport"]));
            }
            set {
                this["LogReport_AutomaticReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int LogReport_AutomaticReportInterval {
            get {
                return ((int)(this["LogReport_AutomaticReportInterval"]));
            }
            set {
                this["LogReport_AutomaticReportInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + F7")]
        public string Config_Shortcut_VirastyarCheckSpell_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarCheckSpell_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarCheckSpell_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + F8")]
        public string Config_Shortcut_VirastyarCheckDates_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarCheckDates_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarCheckDates_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + Control + F8")]
        public string Config_Shortcut_VirastyarCheckNumbers_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarCheckNumbers_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarCheckNumbers_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + F5")]
        public string Config_Shortcut_VirastyarCheckPunctuation_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarCheckPunctuation_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarCheckPunctuation_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + F6")]
        public string Config_Shortcut_VirastyarPinglishConvert_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarPinglishConvert_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarPinglishConvert_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control + Alt + F7")]
        public string Config_Shortcut_VirastyarRefineAllCharacters_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarRefineAllCharacters_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarRefineAllCharacters_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + Control + F6")]
        public string Config_Shortcut_VirastyarPinglishConvertAll_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarPinglishConvertAll_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarPinglishConvertAll_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + Control + F7")]
        public string Config_Shortcut_VirastyarPreCheckSpell_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarPreCheckSpell_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarPreCheckSpell_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Config_Shortcut_VirastyarCheckAllPunctuation_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarCheckAllPunctuation_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarCheckAllPunctuation_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Config_Shortcut_VirastyarAddinSettings_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarAddinSettings_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarAddinSettings_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Config_Shortcut_VirastyarAbout_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarAbout_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarAbout_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift + Control + Space")]
        public string Config_Shortcut_VirastyarAutoComplete_Action {
            get {
                return ((string)(this["Config_Shortcut_VirastyarAutoComplete_Action"]));
            }
            set {
                this["Config_Shortcut_VirastyarAutoComplete_Action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InstallationGuid {
            get {
                return ((string)(this["InstallationGuid"]));
            }
            set {
                this["InstallationGuid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreprocessSpell_CorrectBe {
            get {
                return ((bool)(this["PreprocessSpell_CorrectBe"]));
            }
            set {
                this["PreprocessSpell_CorrectBe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Updater_LastShownVersion {
            get {
                return ((string)(this["Updater_LastShownVersion"]));
            }
            set {
                this["Updater_LastShownVersion"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.virastyar.ir/min-download")]
        public string Updater_DownloadUrl {
            get {
                return ((string)(this["Updater_DownloadUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.virastyar.ir/WhatsNew.txt")]
        public string Updater_WhatsNewUrl {
            get {
                return ((string)(this["Updater_WhatsNewUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogReport_ConfirmationDone {
            get {
                return ((bool)(this["LogReport_ConfirmationDone"]));
            }
            set {
                this["LogReport_ConfirmationDone"] = value;
            }
        }
    }
}
